export const DATA_GET_SUCCESS = 'DATA_GET_SUCCESS';
export const DATA_GET_ERROR = 'DATA_GET_ERROR';
export const DATA_DELETE_ERROR = 'DATA_DELETE_ERROR';
export const DATA_UPDATE_ERROR = 'DATA_UPDATE_ERROR';
export const DATA_CREATE_ERROR = 'DATA_CREATE_ERROR';